server:
  port: 8084

spring:
  application:
    name: shelter-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shelter_db
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.disaster.shelter: DEBUG
